package-lock.json, package.json, playwright-tests/home.spec.ts, src/components/VideoPlayer/index.ts, src/components/VideoPlayer/styles.css, src/components/VideoPlayer/types.ts, src/components/VideoPlayer/videoPlayer.stories.tsx, src/components/VideoPlayer/videoPlayer.tsx
The VideoPlayer component is a reusable React component built using the @vidstack/react library. It renders a video player with a customizable poster image, layout, and controls. The component supports props for configuring the video source, dimensions, poster image, and other attributes.
=> feat: added video player component

.github/workflows/lint.yml
=> ci: added lint workflow

README.md, jest.config.ts, jest.setup.ts, package-lock.json, package.json, src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap, src/components/RecommendedVideoCard/recommendedVideoCard.test.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/RecommendedVideoCard/types.ts
=> test: setup jest and added recommended video card tests

src/components/Button/button.stories.tsx, src/components/Button/button.tsx, src/components/Button/buttonTypes.ts, src/components/Button/index.ts, src/components/Button/styled.tsx, src/components/theme/theme-provider.tsx
=> feat(button): add Button component and its Storybook

.github/PULL_REQUEST_TEMPLATE.md, src/components/theme/theme-provider.tsx
This PR introduces a standardized pull request template to ensure consistency and clarity when submitting PRs. The template includes sections for describing changes, linking related issues, specifying the type of change, and providing a checklist for reviewers and contributors.
- https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/65
1. Created a `.github/PULL_REQUEST_TEMPLATE.md` file in the repository.
2. Added the following sections to the template:
- **Description**
- **Related Issue**
- **Type of Change**
- **Checklist**
- **Additional Notes**
3. Ensured the template aligns with the team's contribution guidelines.
- The template is designed to be flexible and can be updated in the future as needed.
- Feedback from the team is welcome to further improve the template.
=> chore: added pull request template

jest.config.ts, package.json, src/components/Navbar/navbar.tsx, src/components/Sidebar/sidebar.tsx, src/components/Sidebar/styled.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/mainLayoutContainer.stories.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.test.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.tsx
This PR adds **comprehensive Jest unit tests** for the `MainLayoutContainer` component to verify its rendering behavior, conditional logic, and edge cases.  
---
✅ **Added Jest test suite for `MainLayoutContainer`.**  
✅ **Verified correct component rendering** with expected UI elements.  
✅ **Tested conditional rendering logic** based on props and state.  
✅ **Handled edge cases and error scenarios** to ensure robustness.  
✅ **Achieved high test coverage** for `MainLayoutContainer`.  
- **Ensures the correctness of `MainLayoutContainer`.**  
- **Reduces risk of regressions with future changes.**  
- **Improves overall test coverage and project stability.**  
---
🔗 **Reviewers:** _(@farhan2742 @arslanather @wkhaliddev1 @sameeramin)_ …
=> test: add Jest unit tests for MainLayoutContainer

src/components/FeaturedVideoCard/featuredVideoCard.playwright.test.ts Copied!, src/components/FeaturedVideoCard/featuredVideoCard.test.tsx
Link to the associated Taiga tickets: 
- [Featured Video Card]( https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/81?kanban-status=262&kanban-swimlane=22)
What’s Implemented?
✅ Written test cases using jest for FeaturedVideoCard component
✅ Written test cases using playwright for FeaturedVideoCard component
How It Works?
run the test script, test cases will run
Testing & Validation:
=> chore: playwright test cases and jest test cases for featured-video-card

src/app/globals.css, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/FeaturedVideoCard/styled.tsx, src/components/VideoCard/styled.tsx, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx
This PR improves the styling of the **videos grid**, ensuring a more consistent and visually appealing layout.  
---
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/83
🔗 **Reviewers:** _(@farhan2742 @sameeramin @arslanather @wkhaliddev1)_  
✅ **Ready for review!** 🚀
before 
after
=> fix: update styles for videos grid

__mocks__/@reduxjs/toolkit.ts, __mocks__/next/navigation.ts, __mocks__/useLanguage.ts, jest.setup.ts, package-lock.json, package.json, src/components/FeaturedVideoCard/__snapshots__/featuredVideoCard.test.tsx.snap, src/components/FeaturedVideoCard/featuredVideoCard.test.tsx, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/videoCard.test.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/mainLayoutContainer.test.tsx, src/jest/utils/testUtils.tsx
This PR fixes and improves the Jest test cases for the `VideoCard` and `FeaturedVideoCard` components to ensure their correctness and stability.  
---
✅ **Fixed broken Jest test cases** for `VideoCard` and `FeaturedVideoCard`.  
✅ **Updated test assertions** to align with the latest component changes.  
✅ **Ensured correct rendering and interactions** for both components.  
---
- **Ensures stability and correctness** of `VideoCard` and `FeaturedVideoCard`.  
---
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/93
🔗 **Reviewers:** _(@sameeramin @arslanather @wkhaliddev1 @farhan2742)_  
✅ **Ready for review!** 🚀
=> fix: update Jest test cases for VideoCard & FeaturedVideoCard

src/components/FeaturedVideoCard/featuredVideoCard.test.tsx, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/FeaturedVideoCard/styled.tsx, src/components/FeaturedVideoCard/types.ts, src/components/VideoCard/styled.tsx, src/components/VideoCard/types.ts, src/components/VideoCard/videoCard.test.tsx, src/components/VideoCard/videoCard.tsx, src/models/Events/events.ts, src/utils/utils.ts
Link to the associated Taiga tickets: 
- [Show video duration on video cards](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/101?kanban-status=262&kanban-swimlane=22)
What’s Implemented?
✅ Added video duration on video cards
✅ Updated stories for both components
✅ Updated test cases
How It Works?
After logging in to the application, You will be redirected to the video listing page
Testing & Validation:
=> Show video duration over video cards & featured video cards

src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/FeaturedVideoCard/styled.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/Sidebar/styled.tsx, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.tsx, src/components/theme/theme-provider.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/videosListingPage.tsx
This PR implements the typography and color system for the app, ensuring consistent text styling, proper font scaling, and defined color usage across both **light** and **dark** themes.  
@arslanather @farhan2742 @sameeramin 
🔗 [Taiga Task #28](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/28) 🚀
=> feat: updated typography style

src/components/theme/__snapshots__/theme-provider.test.tsx.snap, src/components/theme/theme-provider.test.tsx, src/components/theme/theme-provider.tsx
This PR adds **Jest unit tests** for the `ThemeProvider` component to ensure correct theme switching, persistence, and rendering behavior.  
@arslanather @sameeramin @farhan2742 @wkhaliddev1 
🔗 [Taiga Task #102](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/102) 🚀
=> Test: Added Jest Unit Test for Theme Provider

.github/workflows/e2e.yml, .husky/pre-commit, jest.setup.ts, src/components/FeaturedVideoCard/__snapshots__/featuredVideoCard.test.tsx.snap, src/components/FeaturedVideoCard/featuredVideoCard.test.tsx, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/sidebar.test.tsx, src/components/Sidebar/sidebar.tsx, src/components/ThemeToggle/__snapshots__/themeToggle.test.tsx.snap, src/components/ThemeToggle/themeToggle.tsx, src/components/VideoCard/videoCard.test.tsx, src/features/LoginPage/loginPage.tsx, src/features/VideoDetail/videoDetail.tsx, src/redux/customBaseQuery.ts, src/redux/events/events.test.tsx, src/redux/login/login.test.tsx, src/redux/store/configureStore.tsx, src/redux/store/redux.test.ts, src/services/i18n/i18n.test.ts, src/services/i18n/locales/en/common.json, src/services/i18n/use-language.ts, src/utils/utils.ts
This PR addresses and improves Jest unit test coverage by fixing missing or incomplete test cases, ensuring all key functionalities are properly tested.  
@arslanather @sameeramin @wkhaliddev1 @farhan2742 
🔗 [Taiga Task #106](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/106) 🚀
=> fix: improve Jest unit test coverage

src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap, src/components/RecommendedVideoCard/recommendedVideoCard.stories.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.test.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/RecommendedVideoCard/styled.tsx, src/components/RecommendedVideoCard/types.ts, src/features/VideoDetail/videoDetail.tsx
This PR implements enhancements to the **Suggested Video Card**, improving the user experience by adjusting the display of video information.  
1. **Removed Ratings** – Ratings are no longer displayed on suggested video cards.  
2. **Updated Video Time Display** –  
- Removed timestamp format (`23 May, 2024 / 00:12`).  
- Now displaying **video duration** directly on the video thumbnail.  
@farhan2742 @sameeramin @arslanather @wkhaliddev1
🔗 [Taiga Task #122](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/122) 🚀
=> feat: update suggested video card

jest.config.ts, src/components/Notification/notification.stories.tsx, src/components/Notification/notification.tsx, src/components/VideoCard/videoCard.stories.tsx, src/features/LoginPage/loginPage.tsx, src/redux/customBaseQuery.ts
This PR improves error handling by adding **notifications for failed requests**, ensuring users receive clear feedback when an API request fails.  
- **Added notification system** to display error messages when requests fail.  
- **Handled different error types**, including:  
- Network failures.  
- Server errors (5xx responses).  
- Client errors (4xx responses).  
- **Ensured user-friendly messages** are displayed instead of raw error responses.  
- Simulated **network failures** and verified error notifications appear.  
- Tested different API failure scenarios to confirm correct error messages.  
- Ensured notifications **auto-dismiss after a few seconds** but remain visible long enough for users to notice.  
@farhan2742 @arslanather @sameeramin @wkhaliddev1 
🔗 [Taiga Task …
=> chore: add notification on request failure

src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/sidebar.test.tsx, src/components/Sidebar/sidebar.tsx, src/components/Sidebar/styled.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/hooks/useNavigation.test.ts, src/hooks/useSidebar.ts
This PR updates the **video detail page layout** by moving the **tags** section from the main layout to the **left sidebar**, improving the UI structure and accessibility.  
- **Relocated the tags section** from the main layout to the left sidebar.  
- **Updated the sidebar component** to include the tags list.  
- **Refactored layout styling** to ensure proper alignment.  
- **Adjusted spacing and styling** for a consistent user experience.  
- Verified that **tags are correctly displayed** in the left sidebar.  
- Ensured the **main content layout adjusts properly** after removing tags.  
- **Tested for any UI/UX inconsistencies** after the refactor.  
🔗 [Taiga Task #134](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/134) 🚀
=> refactor: move tags into sidebar

src/components/FeaturedVideoCard/featuredVideoCard.test.tsx, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap, src/components/RecommendedVideoCard/recommendedVideoCard.stories.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/RecommendedVideoCard/styled.tsx, src/components/SearchVideoCard/searchVideoCard.tsx, src/components/VideoCard/videoCard.test.tsx, src/components/VideoCard/videoCard.tsx, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/models/Events/events.ts, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx, src/utils/constants.ts
This PR introduces a **"View Related Videos"** feature on the **video detail page**, allowing users to explore similar content easily.  
- **Fetched and displayed related videos** based on the current video.  
- **Added a "Related Videos" section** below the main video player.  
- **Handled loading and error states** for better user experience.  
🔗 [Taiga Task #113](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/113) 🚀
=> feat: add "View Related Videos" feature

src/components/Sidebar/sidebar.test.tsx, src/components/Sidebar/sidebar.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/mainLayoutContainer.test.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/hooks/useSidebar.ts, src/models/Events/events.ts, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx
This PR introduces a new **"Playlist" API endpoint**, allowing users to fetch and manage playlists efficiently.  
- **Created a new Playlist API endpoint** for fetching playlists.  
- **Implemented request handling and validation** for playlist retrieval.  
- **Ensured proper error handling and response formatting**.  
🔗 [Taiga Task #143](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/143) 🚀
=> feat: add playlist endpoint

.eslintrc.json, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/redux/events/apiSlice.ts
This PR adds **tags to the video page**, improving content discoverability by allowing users to see relevant tags associated with each video.  
- **Displayed tags below the video description** on the video detail page.  
- **Styled tags for better visibility and user interaction**.  
- **Made tags clickable** to allow navigation to related content.  
- **Handled cases where videos have no tags** to prevent UI inconsistencies.  
🔗 [Taiga Task #118](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/118) 🚀
=> feat: display tags on video page

src/components/FeaturedVideoCard/__snapshots__/featuredVideoCard.test.tsx.snap, src/components/FeaturedVideoCard/featuredVideoCard.test.tsx, src/components/FeaturedVideoCard/featuredVideoCard.tsx, src/components/FeaturedVideoCard/styled.tsx, src/components/FeaturedVideoCard/types.ts, src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap, src/components/RecommendedVideoCard/recommendedVideoCard.test.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/RecommendedVideoCard/styled.tsx, src/components/RecommendedVideoCard/types.ts, src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/sidebar.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/mainLayoutContainer.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/SearchResultsPage/types.ts, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/types.ts, src/features/VideosListingPage/videosListingPage.tsx, src/models/Events/events.ts, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx, src/redux/login/login.test.tsx, src/utils/utils.test.ts, src/utils/utils.ts
This PR introduces **infinite scrolling** on the **Events Page**, allowing users to load more events dynamically as they scroll down, improving the browsing experience.  
@farhan2742 @sameeramin @arslanather
🔗 [Taiga Task #110](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/110) 🚀
🔗 [Taiga Task #115](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/115) 🚀
=> feat: add infinite scroll on events page

src/components/FeaturedVideoCard/__snapshots__/featuredVideoCard.test.tsx.snap, src/components/FeaturedVideoCard/styled.tsx, src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap, src/components/RecommendedVideoCard/recommendedVideoCard.test.tsx, src/components/RecommendedVideoCard/recommendedVideoCard.tsx, src/components/RecommendedVideoCard/styled.tsx, src/components/RecommendedVideoCard/types.ts, src/components/SearchVideoCard/searchVideoCard.tsx, src/components/SearchVideoCard/styled.tsx, src/components/SearchVideoCard/types.ts, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx
This PR enhances the **video cards** by displaying the **presenters' names**, providing users with better context about the video content.  
- **Added presenter names** to each video card.  
- **Ensured proper styling and alignment** for a clean UI.  
- **Handled cases where multiple presenters are present**.  
- **Implemented fallback handling** for videos without presenters.  
🔗 [Taiga Task #144](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/144) 🚀
🔗 [Taiga Task #131](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/131) 🚀
=> feat: display presenters on video cards

src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/navbar.tsx, src/components/Select/select.stories.tsx, src/components/Select/select.test.tsx, src/components/Select/select.tsx, src/components/Select/types.ts, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/SearchResultsPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/utils/utils.test.ts, src/utils/utils.ts
This PR introduces **infinite scrolling** on the **Search Page**, enabling users to seamlessly load more search results as they scroll down, improving the browsing experience.  
🔗 [Taiga Task #145](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/145) 🚀
=> Infinite scroll search page

src/components/Navbar/navbar.tsx, src/components/Select/__snapshots__/select.test.tsx.snap, src/components/Select/select.test.tsx, src/components/Select/select.tsx, src/components/Select/styled.tsx, src/components/Select/types.ts, src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/sidebar.test.tsx, src/components/Sidebar/sidebar.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/videosListingPage.tsx
This PR updates the **search and video display functionality** to enhance the **user experience**, improve filtering, and refine sorting options.  
- **Featured Video Visibility**:  
- Ensured the **featured video appears only on the "All" page** and not in filtered views.  
- **Filter Selection Restrictions**:  
- **Users can now select only one playlist or tag at a time** to avoid multiple conflicting filters.  
- **Tag Formatting Updates**:  
- Prefixed **all tags with "#"** (e.g., `#Technology`) for better readability.  
- Removed **"All" from the tag list**, ensuring only relevant tags are shown.  
- Moved **tags into the "Session Details" container** but kept them **outside the text area** so they remain visible regardless of the "Show More/Less" toggle.  
- **Sorting Dropdown …
=> feat: update search & video display functionality

src/components/Navbar/navbar.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.test.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.tsx, src/components/containers/MainLayoutContainer/styled.tsx, src/features/VideoDetail/videoDetail.tsx
This PR introduces a **new sidebar component** to enhance navigation and accessibility within the application. The sidebar is designed to be **responsive, collapsible, and scalable** for future enhancements.  
🔗 [Taiga Task #147](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/147) 🚀
=> feat: add sidebar component

src/components/Navbar/navbar.test.tsx, src/components/Navbar/navbar.tsx, src/components/Select/select.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.test.tsx, src/components/containers/MainLayoutContainer/mainLayoutContainer.tsx, src/components/containers/MainLayoutContainer/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/models/Events/events.ts, src/services/i18n/locales/en/common.json, src/services/i18n/locales/en/videos.json, src/utils/utils.test.ts, src/utils/utils.ts
This PR enhances the video browsing experience by introducing **sorting options** that allow users to organize videos based on their preferences. The new sorting options include:  
- **Newest to Oldest**  
- **Year-Based Filtering**  
- **Added sorting functionality** to the video listing pages.  
- **Updated the sorting dropdown UI** to include the new options.  
- **Ensured backend compatibility** for fetching sorted video data.  
- **Implemented default sorting behavior** (Newest to Oldest).  
- **Optimized query parameters** to handle sorting efficiently.  
- Verified **sorting order updates correctly** based on selection.  
- Ensured **smooth dropdown interactions** with no UI glitches.  
- Checked **backend response correctness** for each sorting type.  
- Confirmed **pagination and …
=> feat: add video sorting by newest, oldest and year filters

src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/SearchResultsPage/styled.tsx
This PR enhances the **responsiveness** of the **Video Search Results** page to ensure optimal user experience across all screen sizes and devices.
🔗 [Taiga Task #159](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/159) 📱🔍
=> Responsive video search results

src/app/[language]/videos/results/page.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/types.ts, src/components/VideoCard/videoCard.stories.tsx, src/components/VideoCard/videoCard.test.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/SearchResultsPage/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/DateFilterDropdown.tsx, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/models/Events/events.ts, src/services/i18n/locales/en/videos.json
This PR merges the **filter** and **sorting dropdowns** into a unified, streamlined component on the Video List page to improve usability and reduce visual clutter.
🔗 [Taiga Task #161](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/161) 🧩📊
=> feat: combine filter & sorting dropdown on video list page

src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/videoCard.test.tsx, src/components/VideoCard/videoCard.tsx, src/components/VideoPlayer/styles.css, src/components/VideoPlayer/videoPlayer.tsx, src/features/VideoDetail/videoDetail.tsx, src/hooks/useNavigation.test.ts, src/hooks/useNavigation.ts, src/services/i18n/locales/en/videos.json
---
---
This PR refines the video viewing experience by improving player behavior, ensuring accurate UI labeling, and enhancing scroll behavior across video-related pages.
---
@farhan2742 @sameeramin @ahmad-arbisoft @arslanather 
---
🔗 [Taiga Task #171] (https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/171)
=> fix: refine video player behavior, UI labels & page scroll handling

next.config.js, src/app/[language]/videos/page.tsx, src/app/[language]/videos/results/page.tsx, src/components/ReadMore/__snapshots__/readMore.test.tsx.snap, src/components/ReadMore/styled.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/theme/theme-provider.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/videoDetail.tsx
---
---
This PR updates key visual and UX details across the platform for improved clarity, consistency, and user comfort, especially in dark mode.
---
🔗 [Taiga Task #168](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/168) ✅
=> feat: update page titles, description formatting & set dark mode as default

src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/videoCard.tsx, src/features/VideosListingPage/videosListingPage.tsx
---
---
Resolves issues with broken or missing video thumbnails across various pages to ensure a consistent and visually complete UI.
---
@farhan2742 @ahmad-arbisoft 
---
🔗 [Taiga Task #176](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/176)
=> fix: resolve broken video thumbnails on video pages

jest.config.ts, src/components/Notification/notification.test.tsx
This PR adds comprehensive **Jest unit tests** for the `Notification` component to ensure proper rendering, behavior, and interactions with different types of messages.
🔗 [Taiga Task](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/104) ✅
=> test: add Jest unit test for Notification component

jest.config.ts, src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/styled.tsx, src/components/Notification/notification.test.tsx, src/components/ReadMore/__snapshots__/readMore.test.tsx.snap, src/components/ReadMore/styled.tsx, src/components/Select/__snapshots__/select.test.tsx.snap, src/components/Select/styled.tsx, src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/styled.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/theme/theme-provider.tsx, src/features/SearchResultsPage/styled.tsx, src/features/VideoDetail/styled.tsx, src/features/VideosListingPage/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/utils/styleUtils.ts
- fix: resolve broken video thumbnails on video pages
- refactor: convert font sizes from px to rem across app
- test: add Jest unit test for Notification component
=> v1.1.2: Fix Release (15 May 2025)

src/app/upload-video/page.tsx, src/features/UploadVideo/styled.tsx, src/features/UploadVideo/uploadVideo.tsx
This PR introduces a **basic video upload page**, allowing users to upload video files to the platform through a clean and accessible interface.
---
- 📁 **File input with validation**  
- Accepts only supported formats: `.mp4`, `.mov`, `.webm`, etc.  
- Rejects unsupported file types with clear error messages  
- 🖱️ **Drag-and-drop support**  
- Users can drag video files into the dropzone area for instant upload interaction  
- Visual feedback when dragging files over the area  
---
@farhan2742 @arslanather @sameeramin
---
🔗 [Taiga Task #164](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/164)
=> feat: implement basic video upload page

jest.config.ts, src/app/globals.css, src/app/layout.tsx, src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/navbar.test.tsx, src/components/Navbar/navbar.tsx, src/components/Navbar/styled.tsx, src/components/Select/styled.tsx, src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap, src/components/Sidebar/sidebar.test.tsx, src/components/Sidebar/sidebar.tsx, src/components/Sidebar/styled.tsx, src/components/ThemeToggle/__snapshots__/themeToggle.test.tsx.snap, src/components/ThemeToggle/themeToggle.test.tsx, src/components/ThemeToggle/themeToggle.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.test.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/theme/colors.ts, src/components/theme/theme-provider.tsx, src/constants/constants.ts, src/features/LoginPage/loginPage.tsx, src/features/LoginPage/styled.tsx, src/features/SearchResultsPage/styled.tsx, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/styled.tsx
This PR finalizes the implementation of **Light Mode UI** throughout the entire application, ensuring a cohesive and polished experience when Light Theme is active.
🔗 [Taiga Task](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/163) 💡🌞
=> feat: apply light mode across all pages

package-lock.json, package.json, src/components/Button/button.tsx, src/components/Button/buttonTypes.ts, src/components/Button/styled.tsx, src/constants/constants.ts, src/features/UploadVideo/form.tsx, src/features/UploadVideo/styled.tsx, src/features/UploadVideo/uploadVideo.tsx, src/features/UploadVideo/videoPicker.tsx
---
---
This PR upgrades the **basic video upload page** by implementing a more **advanced and detailed UI**, enhancing the overall user experience during the video upload process.
---
---
🔗 [Taiga Task](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/166) ✅
=> feat: Implement Advanced Video Upload Page UI

src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideosListingPage/DateFilterDropdown.tsx, src/features/VideosListingPage/videosListingPage.tsx
Update design of "Duration Card" within Suggested Video Card & Fixed production UI issues
- ✅ Updated styling for suggested video card's duration
- ✅ Fixed production pagination issues on "Video Listing Page" & "Search Results Page"
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/183?kanban-status=262&kanban-swimlane=22
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/191?kanban-status=359&kanban-swimlane=22
Ready to review: @farhan2742 @arbisoft-qaisarirfan
=> Update "Duration" styling in Suggested Video Card & Production UI issues fix

src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/navbar.tsx, src/components/Navbar/styled.tsx, src/components/Sidebar/sidebar.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/styled.tsx, src/features/LoginPage/loginPage.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/DateFilterDropdown.tsx, src/features/VideosListingPage/types.ts, src/features/VideosListingPage/videosListingPage.tsx, src/hooks/useNavigation.test.ts, src/models/Events/events.ts, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx
_Provide a concise description of the changes introduced in this PR._
_Explain what this PR accomplishes in a few sentences._
- ✅ _Describe key changes made in this PR._
- ✅ _List major improvements or fixes._
- ✅ _Mention any refactors or optimizations._
1. _Explain the workflow of the implemented changes._
2. _Provide details on how it behaves in different scenarios._
3. _Mention any edge cases handled._
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/XXX
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/192?kanban-status=262&kanban-swimlane=22
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/207?kanban-status=262&kanban-swimlane=22 …
=> UI changes and bug fixes

src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/navbar.tsx, src/components/Navbar/styled.tsx, src/components/Sidebar/sidebar.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/styled.tsx, src/features/LoginPage/loginPage.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideoDetail/styled.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/DateFilterDropdown.tsx, src/features/VideosListingPage/types.ts, src/features/VideosListingPage/videosListingPage.tsx, src/hooks/useNavigation.test.ts, src/models/Events/events.ts, src/redux/events/apiSlice.ts, src/redux/events/events.test.tsx
v1.1.5: Fix Release (19 June 2025)
- Fixed header on top (fixed positioning)
- Fix Login with Google stucked on "Loading..."
- FIxed Pagination Issues
- Removed sorting selector from "Search Results Page"
- Reset filter while moving from one playlist to another or tag
- Change Video description text color
- Make Right Suggestion Bar scrollable on specific height
- Update URl from sessions.arbisoft.com/videos/1 to sessions.arbisoft.com/videos/video-slug
=> v1.1.5: Fix Release (19 June 2025)

src/features/SearchResultsPage/searchResultsPage.tsx
Remove "order_by" param from search results page
- ✅ Remove "order_by" param from search results page
1. _Explain the workflow of the implemented changes._
2. _Provide details on how it behaves in different scenarios._
3. _Mention any edge cases handled._
@arbisoft-qaisarirfan @farhan2742
=> Remove "order_by" param from search results page

src/components/Sidebar/sidebar.tsx, src/features/VideosListingPage/videosListingPage.tsx
Fix the issue related to Pagination where only the sessions of "year 2025" were displayed
- ✅ Fix issue with pagination
- ✅ Fix issue of skeleton loading
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/issue/223
@arbisoft-qaisarirfan @farhan2742
=> Page loading & SIdebar skeleton loader issue fixed

src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/styled.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/redux/events/apiSlice.ts
Sidebar UI & VIdeo Listing Loader enhancement
@arbisoft-qaisarirfan @farhan2742
=> Sidebar UI & VIdeo Listing Loader enhancement

src/components/Sidebar/sidebar.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/components/containers/MainLayoutContainer/styled.tsx, src/features/SearchResultsPage/searchResultsPage.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/redux/events/apiSlice.ts
v1.1.6: Fix Release (24 June 2025)
- Update skeleton loader for sidebar.
- Fix pagination videos issue.
- Remove **order_by** from search API.
- Videos Loading Issue fixed.
- Scrollbar removed from **Right Suggestion Bar**.
=> v1.1.6: Fix Release (26 June 2025)

src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/types.ts, src/components/VideoCard/videoCard.tsx, src/features/VideosListingPage/videosListingPage.tsx
Fixes flickering issue while scrolling All Videos.
Adds fixed height to VideoCard and updates styles to prevent render hesitation
- ✅ Introduced height prop in VideoCard component
- ✅ Updated VideoCardContainer styled component
- ✅ Updated VideoCard snapshot 
1. Ensures each video card has a consistent height
2. Helps VirtuosoGrid avoid miscalculating item positions during scroll
-  Verified scrolling behavior
-  Confirmed layout is stable
N/A
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/211
Check if scroll is smooth and no flicker appears when loading more items.
=> fix: resolve visual flicker while scrolling through All Videos page

.eslintrc.json, package-lock.json, package.json, playwright-tests/setup/login.spec.ts, playwright-tests/videoDetail.spec.ts, src/components/FeaturedSlider/featuredSlider.tsx, src/components/FeaturedSlider/styled.tsx, src/components/FeaturedSlider/types.ts, src/components/Navbar/__snapshots__/navbar.test.tsx.snap, src/components/Navbar/navbar.tsx, src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap, src/components/VideoCard/styled.tsx, src/components/VideoCard/videoCard.tsx, src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap, src/features/VideoDetail/skeletonLoader.tsx, src/features/VideoDetail/videoDetail.tsx, src/features/VideosListingPage/videosListingPage.tsx, src/hooks/useVideoQueryManager.ts, src/redux/customBaseQuery.ts, src/redux/store/configureStore.tsx, src/redux/store/redux.test.ts
=> v1.1.8: Fix Release (5th Aug 2025)
