.github/workflows/e2e.yml
src/components/RecommendedVideoCard/__snapshots__/recommendedVideoCard.test.tsx.snap
src/components/RecommendedVideoCard/recommendedVideoCard.test.tsx
src/jest/utils/testUtils.tsx

This PR updates the GitHub Actions workflow to run both **unit tests (`npm run test`) and E2E tests (`npx playwright test`)** when changes are pushed to `main` or `dev` branches.  
- **Merge into `dev` or `main` and verify that the workflow triggers automatically.**  
---
- Ensures **both unit and E2E tests run consistently** after every merge to `dev` or `main`.  
- Improves **test automation** and prevents issues from reaching production.  
- Simplifies debugging with uploaded Playwright test reports.  
---
🔗 **Reviewers:** _(@sameeramin @arslanather @farhan2742)_  
Related Issue
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/68
✅ **Ready for review!** 🚀

ci: configure gitHub actions to run tests after pr merge

---

src/features/VideoDetail/styled.tsx
src/features/VideoDetail/videoDetail.tsx
src/models/Events/events.ts
src/models/Events/index.ts
src/redux/baseApi.tsx
src/redux/customBaseQuery.ts
src/redux/events/apiSlice.ts
src/redux/parseError.ts

This PR integrates the **Video Detail API** and **Tags List API** into the project, ensuring video details are fetched dynamically and tags are displayed correctly.  
Link to the associated Taiga ticket: https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/69
---
✅ **Integrated Video Detail API** using:  
```plaintext
GET /api/v1/events/videoasset/{id}/
```
- Fetches video details based on the provided `id`.  
- Implements loading, success, and error handling.  
- Ensures TypeScript types are correctly defined.  
✅ **Integrated Tags List API** using:  
```plaintext
GET /api/v1/events/tags/
```
- Fetches and displays the list of available tags.  
- Optimized for performance with caching/memoization where applicable.  
✅ **Updated UI components** to dynamically display video …

feat: integrate video detail API & tags list API

---

src/components/FeaturedVideoCard/featuredVideoCard.playwright.test.ts Copied!
src/components/FeaturedVideoCard/featuredVideoCard.test.tsx
src/components/Sidebar/sidebar.playwright.specs.ts
src/components/Sidebar/sidebar.test.tsx

Link to the associated Taiga tickets: 
- [Siebar test cases](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/89?kanban-status=262&kanban-swimlane=22)
What’s Implemented?
✅ Test cases for sidebar component
How It Works?
After logging in to the application, You will be redirected to the video listing page, and see sidebar items on left
Testing & Validation:

Add playwight test cases for sidebar

---

.github/workflows/e2e.yml
jest.setup.ts
package-lock.json
package.json
src/components/Sidebar/sidebar.test.tsx
src/hooks/useAuth.test.ts

This PR adds **Jest unit tests** for the `useAuth` hook to ensure proper authentication handling, token management, and state updates.  
@arslanather @farhan2742 @sameeramin @wkhaliddev1 
🔗 [Taiga Task #105](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/105) 🚀

test: add Jest unit test for useAuth hook

---

src/components/Select/__snapshots__/select.test.tsx.snap
src/components/Select/select.test.tsx
src/components/Select/select.tsx
src/components/Select/styled.tsx
src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap
src/components/VideoCard/styled.tsx
src/redux/login/login.test.tsx
src/redux/parseError.test.ts
src/redux/parseError.ts
src/redux/store/redux.test.ts

This PR adds **Jest unit tests** for the `Select Dropdown` component to ensure correct functionality, rendering, and user interactions.  
🔗 [Taiga Task #103](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/103) 🚀

test: add Jest unit test for Select Dropdown

---

jest.setup.ts
package-lock.json
package.json
src/components/FeaturedVideoCard/__snapshots__/featuredVideoCard.test.tsx.snap
src/components/Navbar/__snapshots__/navbar.test.tsx.snap
src/components/Navbar/navbar.test.tsx
src/components/Navbar/navbar.tsx
src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap
src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap
src/redux/customBaseQuery.ts
src/redux/events/events.test.tsx
src/redux/login/login.test.tsx
src/utils/utils.test.ts
src/utils/utils.ts

This PR sets up a **mock server** for Jest unit tests, ensuring API calls are properly tested in an isolated environment.  
- **Integrated `jest-fetch-mock`** to mock API responses in tests.  
- **Ensured tests no longer rely on live API calls**, improving reliability and performance.  
- **Updated existing test cases** to use the mock server.  
- Verified API calls return **mocked responses** during tests.  
- Ensured tests **run consistently without external dependencies**.  
- Checked that the mock server correctly intercepts requests and returns expected responses.  
@farhan2742 @arslanather @sameeramin @wkhaliddev1 
🔗 [Taiga Task #133](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/133) 🚀

test: set up mock server for Jest unit tests

---

src/components/containers/MainLayoutContainer/mainLayoutContainer.tsx
src/features/VideoDetail/videoDetail.tsx

This PR removes the **left sidebar** from the **video detail page** to provide a cleaner and more focused user experience.  
- **Removed the left sidebar component** from the video detail page layout.  
- **Updated styling** to adjust content width accordingly.  
- Verified that the **sidebar is no longer visible** on the video detail page.  
- Checked that the **content layout adjusts correctly** without breaking responsiveness.  
- Ensured no regressions or UI misalignment issues occurred.  
🔗 [Taiga Task #135](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/135) 🚀

refactor: remove left sidebar from video detail page

---

src/features/VideoDetail/styled.tsx
src/features/VideoDetail/videoDetail.tsx

This PR updates the **video detail page** by removing the **rating section** and allowing the **video title to take the maximum possible width**, improving readability and UI clarity.  
- **Removed the rating section** from the video detail page.  
- **Updated video title styling** to allow it to expand across available space.  
- **Ensured proper alignment** of the remaining elements after removal.  
🔗 [Taiga Task #120](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/120) 🚀

fix: limit video title to extend up to rating

---

src/components/ReadMore/__snapshots__/readMore.test.tsx.snap
src/components/ReadMore/index.ts
src/components/ReadMore/readMore.stories.tsx
src/components/ReadMore/readMore.test.tsx
src/components/ReadMore/readMore.tsx
src/components/ReadMore/styled.tsx
src/components/ReadMore/types.ts
src/features/VideoDetail/videoDetail.tsx
src/services/i18n/locales/en/common.json

This PR introduces a **"See More" toggle** for the session description on the **video detail page**, allowing users to expand and collapse lengthy descriptions for better readability.  
- **Added a "See More" toggle** to expand/collapse the session description.  
- **Limited the initial description length** to a few lines for a cleaner UI.  
- **Styled the toggle button** for better visibility and usability.  
- Verified that **long descriptions are truncated** initially.  
- Checked that clicking **"See More" expands the full description**.  
- Ensured clicking **"See Less" collapses the description back**.  
🔗 [Taiga Task #136](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/136) 🚀

feat: add "See More" toggle for session description in video detail

---

src/features/VideosListingPage/styled.tsx
src/features/VideosListingPage/videosListingPage.tsx
src/services/i18n/locales/en/videos.json

This PR introduces a **"Filter by Year" dropdown** on the video list page, allowing users to filter videos dynamically based on the selected year.  
- **Added a dropdown filter** for selecting a year.  
- **Populated the dropdown dynamically** based on available years in the video dataset.  
- **Ensured filtering is applied without page reloads** for a seamless user experience.  
- **Implemented a loading state** while the filter is being applied.  
- **Ensured compatibility** with existing filters like tags and playlists.  
- **Added a clear/reset option** to remove the year filter when needed.  
🔗 [Taiga Task #154](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/154) 🚀

feat: add "Filter by Year" dropdown on video list page

---

src/app/[language]/videos/results/page.tsx
src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap
src/components/VideoCard/styled.tsx
src/components/VideoCard/types.ts
src/components/VideoCard/videoCard.stories.tsx
src/components/VideoCard/videoCard.test.tsx
src/components/VideoCard/videoCard.tsx
src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap
src/components/containers/MainLayoutContainer/styled.tsx
src/features/SearchResultsPage/searchResultsPage.tsx
src/features/SearchResultsPage/styled.tsx
src/features/VideoDetail/videoDetail.tsx
src/features/VideosListingPage/styled.tsx
src/features/VideosListingPage/videosListingPage.tsx
src/models/Events/events.ts

This PR introduces a **video preview on hover** feature for video cards to enhance user experience and improve content discoverability.
- Added **video preview playback** on hover for all relevant video cards (featured, suggested, search, etc.).  
- Integrated logic to **play a short muted preview** when the user hovers over a card.  
- Ensured preview stops and resets when the user stops hovering.  
- Optimized video loading and playback to avoid performance issues.  
- Handled fallbacks and ensured graceful behavior if preview is not available.
🔗 [Taiga Task #160](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/160) 🎥👆

feat: add video preview on hover for video card

---

src/components/Navbar/__snapshots__/navbar.test.tsx.snap
src/components/Navbar/styled.tsx
src/components/ReadMore/__snapshots__/readMore.test.tsx.snap
src/components/ReadMore/styled.tsx
src/components/Select/__snapshots__/select.test.tsx.snap
src/components/Select/styled.tsx
src/components/Sidebar/__snapshots__/sidebar.test.tsx.snap
src/components/Sidebar/styled.tsx
src/components/VideoCard/__snapshots__/videoCard.test.tsx.snap
src/components/VideoCard/styled.tsx
src/components/containers/MainLayoutContainer/__snapshots__/mainLayoutContainer.test.tsx.snap
src/components/theme/theme-provider.tsx
src/features/SearchResultsPage/styled.tsx
src/features/VideoDetail/styled.tsx
src/features/VideosListingPage/styled.tsx
src/utils/styleUtils.ts

---
---
Replaced all hardcoded `px` font sizes with `rem` units across the app for better scalability, accessibility, and consistency with modern responsive design practices.
---
* 🔁 Updated all typography (headings, body text, labels, buttons) from `px` to `rem`.
* 📐 Based on a root font size of `16px`, ensuring consistent conversion (`1rem = 16px`).
* 🎯 Affected components include:
* Global styles and theme files
* Typography components and styled elements
* Reusable UI components (e.g., Button, Card, Modal)
---
* ♿ Improved accessibility through user-controlled scaling
* 📱 Better responsive behavior across screen sizes
* 🔧 Easier theming and maintenance of font sizing
---
@farhan2742 @ahmad-arbisoft 
---
🔗 [Taiga Task](https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us …

refactor: convert font sizes from px to rem across app

---

package-lock.json
package.json
src/app/layout.tsx

Added Google Tag Manager (GTM) support using the official @next/third-parties package.
This PR sets up GTM in the app using Next.js’s recommended approach. It ensures GTM loads on all pages without manually adding script tags.
- ✅ Installed @next/third-parties
- ✅ Added GoogleTagManager
1. GTM is loaded using the <GoogleTagManager /> component from @next/third-parties.
2. It handles both the script and noscript parts automatically.
3. The setup works across all pages and follows Next.js best practices.
-  GTM loads correctly in browser
-  Verified it using  Google’s official [Tag Assistant  chrome extension] 
-  Code follows project standards
N/A
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/224
You can verify the GTM …

#224 Integrating GTM

---

src/components/Sidebar/sidebar.tsx
src/features/VideosListingPage/skeletonLoader.tsx
src/features/VideosListingPage/types.ts
src/features/VideosListingPage/videosListingPage.tsx
src/hooks/useVideoQueryManager.ts

Refactored video listing architecture to introduce a new hook `useVideoQueryManager` that centralizes query param management, page control, and API parameters. This eliminates race conditions and stale data UI bugs.
This PR resolves major video listing issues related to stale data, incorrect pagination, and unwanted API calls.  
The new structure is cleaner, scalable, and easier to maintain for future enhancements.
- ✅ Introduced `useVideoQueryManager` hook
- ✅ Reset `videoData` for page 1 before new API calls to prevent stale renders
- ✅ Debounced API call on query param change
- ✅ SkeletonLoader separate component
- ✅ Controlled page reset using query param dependencies
- ✅ Separated featured section logic.
1. A new custom hook useVideoQueryManager manages all query param logic in one …

refactor: restructure video listing with useVideoQueryManager hook to fix scroll and filtering issues

---

src/features/VideoDetail/videoDetail.tsx
src/models/Events/events.ts
src/redux/events/apiSlice.ts
src/redux/events/events.test.tsx

Added pagination support for recommendations API and implemented infinite scroll on the video detail page to lazyload videos.
This PR improves the recommendations section on the video detail page by adding backend pagination support in the API slice and implementing infinite scroll on the frontend to load videos as the user scrolls.
- ✅ Integrated pagination parameters (page, page_size) into the recommendation endpoint in apiSlice.
- ✅ Implemented infinite scroll using react-virtuoso on the video detail page.
1. The recommendation endpoint now accepts id, page, and page_size to paginate results from the backend.
2. On the frontend, react-virtuoso handles fetching new pages as the user scrolls, appending them to the list dynamically.
-  Tested all relevant functionalities.
- Verified …

feat: integrate pagination with infinite scroll for recommendations

---

src/hooks/useVideoQueryManager.ts

Added default ordering of videos by `-event_time`.
This PR ensures videos are sorted by Newest first by default.
- ✅  Applied default ordering -event_time fallback in useVideoQueryManager
1. If order is in the URL, use it. otherwise, default to -event_time in the query manager.
2. Default order applies even when filters are cleared or changed.
N/A
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/issue/235
Please verify that `-event_time` is applied by default.

fix: set default sorting to newest first

---

playwright-tests/setup/login.spec.ts
playwright-tests/videoDetail.spec.ts
src/features/VideoDetail/skeletonLoader.tsx
src/features/VideoDetail/videoDetail.tsx

Added Playwright tests for the VideoDetail page and introduced a login test to save authentication state.
This PR covers e2e tests for the VideoDetail page and adds a login test to persist authentication for future tests.
- ✅ Added Playwright tests for VideoDetail page
- ✅ Added login test to save authentication state
- ✅ Extracted SkeletonLoader as a separate component for video player loading skeletons.
1. The login test saves the authenticated state for reuse in other tests.
2. VideoDetail tests check page rendering and navigation behavior.
3. Manual login is required before running tests to ensure valid session.
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/137
- First run: `npx playwright test …

test: add e2e tests for VideoDetail component with Playwright

---

src/hooks/useVideoQueryManager.ts

Fixes the issue where the featured video was not displaying on pages other than the main videos page.
This PR removes an incorrect API filter that excluded featured videos, ensuring they appear consistently across all pages.
- ✅ Removed `is_featured=false` from apiParams in `useVideoQueryManager` hook.
- ✅ Verified featured videos now show correctly on all relevant pages.
1. Removed `is_featured=false` from `useVideoQueryManager` to ensure featured videos appear across all pages.
- Tested featured videos visibility on all pages.
- Verified API response includes featured videos.
_(Add screenshots, videos, or GIFs if necessary.)_
https://projects.arbisoft.com/project/arbisoft-sessions-portal-20/us/208
Ensure featured videos appear correctly on all …

fix: ensure featured video appears on all relevant pages

---

src/redux/customBaseQuery.ts
src/redux/store/configureStore.tsx
src/redux/store/redux.test.ts

Fixes an issue where users logging in via Google in incognito mode were logged out upon page reload due to improper Redux persistence.
This PR addresses a session persistence issue in incognito mode by updating the Redux store setup. The root cause was linked to the use of persistCombineReducers, which has been replaced with a more reliable and modern approach using combineReducers and persistReducer.
- ✅ Replaced persistCombineReducers with combineReducers and wrapped it using persistReducer
- ✅ Removed custom logout handler from rootReducer
- ✅ Updated store configuration to ensure session is properly persisted
1. Previously, `persistCombineReducers` was used, which is outdated or incompatible in some edge cases
2. Replacing it with a standard `combineReducers` wrapped by …

fix: frequent logout and session expiry issues

---

.github/workflows/build-and-push-container-image.yml

This PR implements automated deployment triggering in the CI/CD pipeline to streamline the frontend deployment process after successful container builds.
Adds automated deployment workflow dispatch functionality to the existing `build-and-push-container-image` workflow, enabling seamless deployment triggers after successful container builds.
- ✅ Added GitHub App token creation step for secure deployment repository access
- ✅ Integrated workflow dispatch mechanism using GitHub Script action
- ✅ Added frontend version parameter passing (branch name) to deployment workflow
- ✅ Configured environment variables for deployment repository targeting
1. After successful container build and push, creates a temporary GitHub App token using configured app credentials
2. Uses the token to authenticate …

feat: add automated deployment trigger to build workflow
